### ISSUE TITLE
Icon components & helpers

### ISSUE THREAD

**Issue by brunnerjosh** [HelpfulHuman/HelpfulUI#14]
We need to find a way for this to work with any type of icon font set or even background images.  May be good to look at using some kind of a config set up like:

``` stylus
$theme__icons-{icon name}

icon(chevron-down) // returns value of $theme__icons-chevron-down
```

**Comment by NickGlenn** [comment]
Configuration can look like this:

``` stylus
$icons.default = 'customIconSet'
$icons.customIconSet = {
  selector: 'my-icon'
  font-family: 'Custom Icon Set'
  generate-classes: true
  glyphs: {
    arrow-down: '\e200'
  }
}
```

The `generate-classes` property does what it says for the icon set and would create a component and modifier set for the icon and glyphs.

``` stylus
.my-icon {
  font-family: 'Custom Icon Set';
}

.my-icon.\+arrow-down:before {
  content: '\e200'
}
```

If you want to specify icons on specific elements instead...

``` styl
.foo
  icon arrow-down

// you can also specify a different icon set be passing 2 arguments
.bar
  icon fa close
```

Would translate to:

``` css
.my-icon, .foo {
  font-family: 'Custom Icon Set'
}

.fa, .bar {
  font-family: 'Font Awesome'
}

.foo {
  content: '\e200'
}

.bar {
  content: '...'
}
```
